export const KAR_BASIC_SAMPLES = [
  {
    name: 'HELLO',
    source: [
      'PRINT "HELLO, WORLD!"',
      'VAR LIMIT = INT 3.8',
      'VAR COUNT = 0',
      'VAR READY = SIGN -1 < 0',
      'IF READY THEN',
      'PRINT "LET\'S COUNT TO ", LIMIT',
      'END IF',
      'FOR I=1 TO LIMIT',
      'PRINT "COUNT ", I',
      'END FOR',
      'WHILE COUNT < 2',
      'PRINT "RND 1-10: ", RND 1, 10',
      'COUNT = COUNT + 1',
      'END WHILE',
      'INPUT "WHAT IS YOUR NAME? " USER',
      'IF USER = "" THEN',
      'PRINT "HELLO, STRANGER."',
      'ELSE',
      'PRINT "HELLO, ", USER',
      'END IF',
      'PRINT "TIMER: ", TIMER',
      'PRINT "ABS -5 = ", ABS -5',
      'PRINT "INT 3.9 = ", INT 3.9',
      'PRINT "SIGN -7 = ", SIGN -7',
      'SEED 123',
      'PRINT "SEEDED RND: ", RND 10',
      '',
    ].join('\n'),
  },
  {
    name: 'FIBB',
    source: [
      'VAR A = 0',
      'VAR B = 1',
      'VAR COUNT = 0',
      'VAR NEXT_VAL = 0',
      'PRINT "FIBB:"',
      'WHILE COUNT < 10',
      'PRINT A',
      'NEXT_VAL = A + B',
      'A = B',
      'B = NEXT_VAL',
      'COUNT = COUNT + 1',
      'END WHILE',
      '',
    ].join('\n'),
  },
  {
    name: 'GUESS',
    source: [
      'SEED TIMER',
      'VAR TARGET = RND 1, 100',
      'VAR TRIES = 5',
      'VAR WON = 1 = 2',
      'PRINT "I\'M THINKING OF A NUMBER FROM 1 TO 100."',
      'WHILE TRIES > 0 AND NOT WON',
      'PRINT "TRIES LEFT: ", TRIES',
      'INPUT "YOUR GUESS? " GUESS',
      'IF GUESS = TARGET THEN',
      'PRINT "YOU GOT IT!"',
      'WON = 1 = 1',
      'ELSE IF GUESS < TARGET THEN',
      'PRINT "TOO LOW"',
      'ELSE',
      'PRINT "TOO HIGH"',
      'END IF',
      'TRIES = TRIES - 1',
      'END WHILE',
      'IF NOT WON THEN',
      'PRINT "OUT OF TRIES. THE NUMBER WAS ", TARGET',
      'END IF',
      '',
    ].join('\n'),
  },
];
